/*
 * RE-AGENT-BANNER: Apple System 7.1 Finder Function Prototypes
 * Derived from Finder ROM code (Ghidra)
 * Architecture: Motorola 68k, Classic Mac OS ABI
 * Generated by reimplementation agent (coord-0004)
 * Source evidence: mappings.json, evidence.curated.json
 */

#ifndef FINDER_PROTO_H
#define FINDER_PROTO_H

#include "SystemTypes.h"

/* Forward declarations */

#include "SystemTypes.h"

#include "Finder/finder_types.h"

/* Function prototypes derived from mappings.json */

/* FinderResourceEntry - evidence: mappings.json address 0x00000000 */
void FinderResourceEntry(void);

/* MainEventLoop - evidence: mappings.json address 0x0001184f */
OSErr MainEventLoop(EventRecord* event, WindowPtr window, MenuHandle menu,
                   short item, long data, Ptr userData);

/* HandleFileOperation - evidence: mappings.json address 0x0002e706 */
OSErr HandleFileOperation(FSSpec* fileSpec, short operation);

/* Utility functions (inferred from Classic Mac OS patterns) */
void InitializeFinder(void);
void ShutdownFinder(void);
Boolean ProcessEvent(EventRecord* event);
void UpdateMenus(void);
void HandleMenuChoice(long menuResult);
void HandleMouseDown(EventRecord* event);
void HandleKeyDown(EventRecord* event);
void HandleUpdate(EventRecord* event);
void HandleActivate(EventRecord* event);

/* File management functions */
OSErr CopyFile(FSSpec* source, FSSpec* dest);
OSErr MoveFile(FSSpec* source, FSSpec* dest);
OSErr DeleteFile(FSSpec* fileSpec);
OSErr RenameFile(FSSpec* fileSpec, ConstStr255Param newName);

/* Window management */
WindowPtr CreateFinderWindow(Rect* bounds, ConstStr255Param title);
void CloseFinderWindow(WindowPtr window);
void UpdateFinderWindow(WindowPtr window);

/* Menu management */
void SetupMenuBar(void);
void EnableMenuItems(void);
void DisableMenuItems(void);

/* Desktop management */
void RefreshDesktopRect(const Rect* rect);

#endif /* FINDER_PROTO_H */

/*
 * RE-AGENT-TRAILER-JSON: {
 *   "file": "include/finder_proto.h",
 *   "generated": "2025-09-17T22:25:00Z",
 *   "evidence_sources": [
 *     "mappings.json",
 *     "evidence.curated.json"
 *   ],
 *   "functions_declared": 18,
 *   "evidence_based_functions": 3,
 *   "inferred_functions": 15,
 *   "provenance_density": 0.17,
 *   "confidence": 0.65
 * }
 */